### ISSUE TITLE
Problem with mapping the workspace

### ISSUE THREAD

**Issue by Zarnack** [NVlabs/industreallib#1]
Hi,
I am currently trying to reproduce your setup. Unfortunately I am running into issues regarding the workspace mapping and detecting the objects.  
After doing the hand-eye calibration (calibrate_extrinsics.py) the April tag is detected at the correct position in the robot coordinate frame. After calibrating, I tried to detect a peg. The peg is detected and its bounding box is overlayed correctly, but the position in the robot frame is not correct. Especially the y-axis is usually of by >15cm.

Instead of a Intel D415 camera, I am using a Intel D455. I therefore adjusted the resolution to 1280x800. The April tag is always detected successfully.

During debugging several questions came up:  
- What is the active_pixel_ratio? By default, it is set to 0.6. The accompanying link to the [April Tag User Guide](https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide) does not describe this parameter. It seems like it is only multiplied during calculation of the tag_active_length:  
`tag_active_length = tag_length * 0.0254 * tag_active_pixel_ratio`

- What exactly is the tag length? Is it the length of the whole tag or just the length between the inner black border ([like shown here?](https://github.com/AprilRobotics/apriltag/blob/master/tag_size_48h12.png))

- The default amount of tag detections during the intrinsic calibration is 64. This seems to be a lot. Is this a reasonable number? Could you recommend a lower amount that gives "OK" results just for testing? 

- Do you have any clues on what the issue could be? 

Nevertheless, so far this is a great project and paper!

**Comment by ynarang** [comment]
Hi @Zarnack,

Thanks for your questions!

Re: tag_length and active_pixel_ratio: 

We define tag_length as the outermost length of the AprilTag (including all border pixels) when printed. (Note: You may need to modify your printer settings in order to print to scale, e.g., to ensure that when you print an image that is 6 inches in length, it's actually 6 inches in real life.)

We define active_pixel_ratio as the ratio of "the number of pixels along an edge between detection corners" and "the number of pixels along an edge between outer corners." For example, for the [48h12 tag](https://github.com/AprilRobotics/apriltag/blob/master/tag_size_48h12.png) that you found in the AprilTag user guide, there are 6 pixels between the detection corners, and 10 pixels between outer corners, so the active_pixel_ratio would be 0.6

Re: default number of tag detections: Yes, 64 is high. We've found improved accuracy when using a high number of detections, but for quick tests, I believe 20-30 should be more than sufficient.

There aren't that many parameters to tune in our [config file](https://github.com/NVlabs/industreallib/blob/main/src/industreallib/perception/configs/perception.yaml), so I don't have any other strong guesses as to what could cause ~15 cm of error, but checking the above values seems like the right place to start. Another great resource is the guide for the [easy-handeye](https://github.com/IFL-CAMP/easy_handeye) library, which has some useful debugging tips for a similar procedure.

Best,
Yash
