### ISSUE TITLE
Need for action_scale

### ISSUE THREAD

**Issue by wredsen** [NVlabs/industreallib#2]
At first: Thank you for this amazing project bringing RL from simulation to real hardware!

I find it difficult to understand the need for the action_scale factor inside the [instance_configs](https://github.com/NVlabs/industreallib/blob/main/src/industreallib/tasks/instance_configs/). 

Couldn't they cause a sim2real gap, due to a magic number beeing multiplied with the "correct" actions from simulation? 

All information about this action_scale factor I could find was in the [industreal paper](https://arxiv.org/pdf/2305.17110.pdf) in the caption "TABLE XII: Real-world evaluation parameters for Insert. Action scales are scalars applied to position and rotation actions in order to bring robot execution speeds to within comfortable limits". This seems like they are some magic numbers to limit the steps in impedance control target values. Couldn't this be performed by some proper limits of the action space in simulation?

Best regards,
Konstantin

**Comment by ynarang** [comment]
Hi Konstantin,

Thank you for the positive feedback! We hope this repo and project will be useful for your work.

Regarding the action scale: an important thing to note as that we actually train with an action scale as well. ([Here](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/aeed298638a1f7b5421b38f5f3cc2d1079b6d9c3/isaacgymenvs/tasks/industreal/industreal_task_pegs_insert.py#L727-L730) is an example for a peg insertion task.) In other words, we are indeed limiting the action space in simulation.

The way we interpret this is translating the actions from their default range of [-1, 1] to a physically-meaningful range for the low-level controller. Empirically, this has improved the convergence rate and (at times) the asymptotic performance of our policies.

Another thing to note is that when we started working on the IndustReal project, we typically trained in simulation and tested in the real world with the same nominal controller. We used essentially used the same gains and action scales in both sim and real. ([Here](https://github.com/NVlabs/industreallib/blob/72a964b9a00cd15b4fc54b7b0eda74454b8b05e9/src/industreallib/tasks/instance_configs/reach.yaml#L40C1-L40C57) is an example for our real-world Reach policy, which used the same action scales in simulation as the link above.)

While dealing with the issue of steady-state error in the real world, we eventually developed PLAI. We continued to train the same way in simulation (there was little advantage to training with PLAI, as our simulated dynamics did not have the nonlinearities of the real world), but deployed our policies in the real world using PLAI. As PLAI essentially integrates policy actions, the dynamics introduced by the controller are altered, and the action scales need to be adjusted (typically reduced) in order to ensure safe execution on the real robot.

Those action-scale adjustments might require a bit of tuning for a given task, but in our experience, it has been relatively quick. In more recent work, which we hope to release soon, we also maintain the same gains and action scales across all tasks.

Best,
Yash

**Comment by wredsen** [comment]
Thank you for this comprehensive reply!

It makes a lot of sense limiting or scaling the aciton values. So you did not play with this values at the deployment stage on the physical hardware, but instead always used the same action scale values in sim and real when **not using PLAI**?

I really like the concept of PLAI as some kind of integrative control part and played around with it on a sim2real example.  Do you have some more theoretical research on this besides the Appendix in the industreal paper?

> In more recent work, which we hope to release soon, we also maintain the same gains and action scales across all tasks.

So you won't change the values between lets say reach and insert, but still have the discrepancy between sim and real introduced by PLAI?

**Comment by ynarang** [comment]
That's correct, when not using PLAI, we used the same action scale values in sim and real.

Great to hear the feedback on PLAI -- especially that you've tried it out! We haven't done more theoretical research on PLAI beyond the brief analysis in the Appendix of the paper. However, we'd definitely welcome it from any members of the community that might be interested.

Re: the recent work, we do have a discrepancy between the sim (nominal) and real (PLAI) action scales, but we deploy the same set of PLAI action scales across all tasks.
